"$schema" = 'https://starship.rs/config-schema.json'

format = """
[î‚¶](fg:zero)\
$os\
$shell\
$sudo\
$username\
$hostname\
$container\
[ ](bg:zero)\
[î‚°](fg:zero bg:one)\
$directory\
[î‚°](fg:one bg:two)\
$git_branch\
$git_status\
$git_commit\
[î‚°](fg:two bg:four)\
[(\
$c\
$cmake\
$elixir\
$elm\
$golang\
$python\
$lua\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$perl\
$scala )](bg:four)\
[î‚°](fg:four bg:five)\
$docker_context\
$package\ 
[î‚° ](fg:five)$all\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# colours, why isn't this a part of the preset
palette = 'default'

[palettes.default]
zero      = '#9A348E'
one       = '#DA627D'
two       = '#FCA17D'
three     = '#86BBD8'
four      = '#06969A'
five      = '#33658A'
bright    = '#e5e5e5'
dark      = 'bright-black'

[palettes.test]
zero      = '#ff0000'
one       = '#00ff00'
two       = '#0000ff'
three     = '#ffff00'
four      = '#00ffff'
five      = '#ff00ff'
bright    = '#e5e5e5'
dark      = 'bright-black'

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:zero"
style_root = "bg:zero italic"
format = '[$user]($style)'
disabled = false

[hostname]
ssh_only = true
ssh_symbol = "@"
format = '([$ssh_symbol]($style))[$hostname]($style)'
style = "bg:zero fg:textlight"

[sudo]
format = '[$symbol ]($style)'
symbol = "ï‚­"
style = "bg:zero"
disabled = false

[os]
format = '[$symbol ]($style)'
style = "bg:zero"
disabled = false

[os.symbols]
Android = "ï…»"
Arch = "ó°£‡"
Debian = "ïŒ†"
Linux = "ïŒš"
NixOS = "ïŒ“"
Raspbian = "ïŒ•"
Windows = "ó°²"

[shell]
format = '[$indicator]($style)'
style = "bg:zero"
disabled = true
zsh_indicator = ""
bash_indicator = "î¯Š"
powershell_indicator = "ó°¨Š"
pwsh_indicator = "î¯‡"

[directory]
style = "bg:one"
format = "[ $path ]($style)([$read_only ]($style))"
read_only = "ï€£"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ó°ˆ™"
"Downloads" = "ï€™"
"Music" = "ï€"
"Pictures" = "ï€¾"
"Images" = "ï€¾"
"Videos" = "ï€ˆ"
"/mnt/c" = "C:"
# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "

[git_branch]
symbol = "ï˜"
style = "bg:two fg:bright"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:two fg:bright"
format = '([$all_status$ahead_behind ]($style))'

[git_commit]
tag_symbol = ' ï’ '
style = "bg:two fg:bright"

[c]
symbol = "î˜"
style = "bg:four"
format = '[ $symbol( $version)]($style)'

[cpp]
symbol = "ó°™²"
style = "bg:four"
format = '[ $symbol( $version)]($style)'

[cmake]
symbol = "î”"
style = "bg:four"
format = '[ $symbol( $version)]($style)'

[elixir]
symbol = "î‰µ"
style = "bg:four"
format = '[ $symbol( $version)]($style)'

[elm]
symbol = "î˜¬"
style = "bg:four"
format = '[ $symbol( $version)]($style)'

[golang]
symbol = "î˜§"
style = "bg:four"
format = '[ $symbol( $version)]($style)'

[python]
symbol = "ó°Œ "
style = "bg:four"
format = '[ $symbol( $version)]($style)'

[lua]
symbol = "ó°¢±"
style = "bg:four"
format = '[ $symbol( $version)]($style)'

[gradle]
symbol = "ğŸ…¶"
style = "bg:four"
format = '[ $symbol( $version)]($style)'

[haskell]
symbol = "î·"
style = "bg:four"
format = '[ $symbol( $version)]($style)'

[java]
symbol = "î‰–"
style = "bg:four"
format = '[ $symbol( $version)]($style)'

[julia]
symbol = "î˜¤"
style = "bg:four"
format = '[ $symbol( $version)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:four"
format = '[ $symbol( $version)]($style)'

[nim]
symbol = "ó°†¥"
style = "bg:four"
format = '[ $symbol( $version)]($style)'

[rust]
symbol = "î¨"
style = "bg:four"
format = '[ $symbol( $version)]($style)'

[scala]
symbol = "îœ·"
style = "bg:four"
format = '[ $symbol( $version)]($style)'

[perl]
symbol = "î™¾"
style = "bg:four"
format = '[ $symbol( $version)]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "bg:five"
format = '[ $symbol $context ]($style)'

[package]
symbol = "î¬©"
style = "bg:five"
format = '([ $symbol $version ]($style))'

[cmd_duration]
format = "[$duration]($style) "
style = "bold yellow"

[time]
disabled = true
time_format = "%l:%M %P" 
style = "fg:dark"
format = '[ $time ]($style)'

[character]
success_symbol = "[â¤ ](fg:dark bold)"
error_symbol = "[â¤ ](fg:dark bold)"
disabled = true

[line_break]
disabled = true