name = "system"
name_pretty = "System Commands"
icon = "laptop"
global_search = true
search_name = true

[[entries]]
text = "Start Immich"
subtext = "systemctl start immich-compose.service"
keywords = ["docker", "immich"]
icon = "photos"
actions = { "start" = "systemctl start immich-compose.service" }

[[entries]]
text = "Start Docker"
subtext = "systemctl start docker.service"
keywords = ["docker"]
icon = "docker"
actions = { "start" = "systemctl start docker.service" }

[[entries]]
text = "Stop Docker"
subtext = "systemctl stop docker.service docker.socket"
keywords = ["docker", "immich"]
icon = "stop"
actions = { "stop" = "systemctl stop docker.service docker.socket" }

[[entries]]
text = "Restart Elephant"
subtext = "systemctl --user restart elephant.service"
keywords = ["elephant"]
icon = "reload"
terminal = true
actions = { "restart" = "systemctl --user restart elephant.service" }