force_keyboard_focus = false    # forces keyboard forcus to stay in Walker
close_when_open = true          # close walker when invoking while already opened
selection_wrap = true           # wrap list if at bottom or top
click_to_close = true           # closes walker if clicking outside of the main content area
global_argument_delimiter = "#" # query: firefox#https://benz.dev => part after delimiter will be ignored when querying. this should be the same as in the elephant config
exact_search_prefix = "'"       # disable fuzzy searching
theme = "wide"               # theme to use
disable_mouse = false           # disable mouse (on input and list only)

[shell]
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[placeholders]
"default" = { input = "Search", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"

[keybinds]
close = ["Escape"]
next = ["Down"]
previous = ["Up"]
toggle_exact = ["ctrl e"]
resume_last_query = ["ctrl r"]
quick_activate = []

[providers]
default = [
  "desktopapplications",
  "calc",
  "websearch",
] # providers to be queried by default
empty = ["desktopapplications"] # providers to be queried when query is empty
max_results = 50 # global max results

[providers.sets] # define your own defaults/empty sets of providers
[providers.max_results_provider] # define max results per provider in here

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[[providers.prefixes]]
prefix = "~"
provider = "files"

[[providers.prefixes]]
prefix = "."
provider = "symbols"

[[providers.prefixes]]
prefix = "\\"
provider = "unicode"

# [[providers.prefixes]]
# prefix = "!"
# provider = "todo"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "??"
provider = "websearch"

[[providers.prefixes]]
prefix = ":"
provider = "clipboard"

[[providers.prefixes]]
prefix = ">"
provider = "runner"

[[providers.prefixes]]
prefix = "!"
provider = "windows"

[providers.clipboard]
time_format = "%d.%m. - %H:%M" # format for the clipboard item date

[providers.actions]
dmenu = [{ action = "select", default = true, bind = "Return" }]
